vich_uploader:
    db_driver: orm

    mappings:
        user_avatars:
            uri_prefix: '%user_avatars%'
            upload_destination: '%kernel.project_dir%/public%user_avatars%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
        home_images:
            uri_prefix: '%home_images%'
            upload_destination: '%kernel.project_dir%/public%home_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
