name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2

        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.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}}
          publish_dir: ./dist
